image: amitaarya17/docker-maven-chrome:jdk-8

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn test -Dtest=cucumber.testrunner.CucumberTestSuite.java